name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run:   | 
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm install
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm run build

      - name: Change to gh pages
        run:   | 
            mkdir ${GITHUB_WORKSPACE}/../dist
            mv ${GITHUB_WORKSPACE}/vite-react-project/dist/* ${GITHUB_WORKSPACE}/../dist/
            git checkout gh-pages
            rm -rf ${GITHUB_WORKSPACE}/vite-react-project
            mv ${GITHUB_WORKSPACE}/../dist/* ${GITHUB_WORKSPACE}
            git add .
            git commit -am "github pages"
            git push

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
      #     publish_dir: ${GITHUB_WORKSPACE}/vite-react-project/dist

