name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run:   | 
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm install
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ${GITHUB_WORKSPACE}/vite-react-project/dist
      
      - name: List Files Dist
        run: ls -la ${GITHUB_WORKSPACE}/vite-react-project/dist

      - name: Tree Files Dist
        run: tree ${GITHUB_WORKSPACE}/vite-react-project/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          publish_dir: ${GITHUB_WORKSPACE}/vite-react-project/dist

