name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run:   | 
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm install
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm run build          

      - name: Change to gh pages
        run: cd ${GITHUB_WORKSPACE}/vite-react-project && npm run deploy

