name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run:   | 
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm install
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm run build          

      - name: Change to gh pages
        run: |
            ##git config --global user.email "khrist14n@gmail.com"
            ##git config --global user.name "khrist14n"
            cd ${GITHUB_WORKSPACE}/vite-react-project && npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}


